### ISSUE TITLE
name label clashes with series name

### ISSUE THREAD

**Issue by fmoessbauer** [prometheus/graphite_exporter#39]
Currently it is not possible to set a label 'name', as this keyword is reserved for the series name. However it would be useful to be able to set this label to be compatible with other exporters:

Telegraf **inputs.net** exporter:
`diskio_read_bytes{host="kronos",instance="192.168.x.x.xxxx",job="linux-server",name="vda"}`

To be backwards-compatible some kind of escaping could be used.

**Comment by matthiasr** [comment]
This is essentially the same issue as prometheus/statsd_exporter#90.

Since StatsD and Graphite have  essentially the same metric model, we keep running into these parallel issues, but the fixes are no longer portable because the two have completely diverged.

I think the solution I would prefer for this would be to

- break out the statsd exporter mapper into a package (it is the more advanced one)
- switch the graphite exporter to use the same YAML-based config format (#38)
- and use the statsd mapper here (#37)

This will solve this issue as well, since the statsd mapper already treats the name separately from labels.

There may be other parts of the statsd exporter that could be modularized and re-used, but the mapper is the obvious candidate.

**Comment by matthiasr** [comment]
Fixed by #52.

**Comment by efficks** [comment]
@matthiasr This issue does not seems fixed. The problem still appear with my config with version 0.4.2.
